name: eyeofcthulhu
version: '${project.version}'
main: me.zelha.eyeofcthulhu.Main
api-version: 1.8.9
authors: [ zel ]
commands:
  add:
    usage: /<command> (color) (int)
  remove:
    usage: /<command>
  sout:
    usage: /<command>
